### ISSUE TITLE
site_prism is locked to site_prism-all_there v0.3, so it's not possible to install latest version (1.0.1)

### ISSUE THREAD

**Issue by arg** [site-prism/site_prism#108]
## Environment
- Operating System (Mac / Windows / Ubuntu e.t.c.):
  **Unrelated**
- What Gems / Versions you are using (Specifically `site_prism` and `capybara`)
  **site_prism v3.7.3, site_prism-all_there v1.0.1 (trying to install)**
- How you're interacting with the Framework (Cucumber Tests / RSpec Units / Minitest)
  **Unrelated**
- Browser/s Driver/s being used - with version numbers
  **Unrelated**

## Expected Behavior
Able to install both latest versions of site_prism and site_prism-all_there

## Actual Behavior
```sh
# after adding site_prism-all_there to Gemfile

~/dev/app$ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
You have requested:
  site_prism-all_there ~> 1.0, >= 1.0.1

The bundle currently has site_prism-all_there locked at 0.3.2.
Try running `bundle update site_prism-all_there`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`

~/dev/app$ bundle update site_prism-all_there
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "site_prism-all_there":
  In Gemfile:
    site_prism-all_there (~> 1.0, >= 1.0.1)

    site_prism (~> 3.7) was resolved to 3.7.3, which depends on
      site_prism-all_there (>= 0.3.1, < 1.0)
```

## Steps to reproduce
1. Add both gems to `Gemfile`:
   ```ruby
   # Gemfile
   ...
   gem 'site_prism', '~> 3.7'
   gem 'site_prism-all_there', '~> 1.0', '>= 1.0.1'
   ...
   ```
2. run `bundle install`

**Comment by luke-hill** [comment]
I haven't unlocked this yet. I was planning on doing this last year but then a lot of flux came about.
