### ISSUE TITLE
Update graphic associated with Betterment in the wiki

### ISSUE THREAD

**Issue by CelticMajora** [site-prism/site_prism#110]
# Issue to raise for SitePrism wiki
The Betterment logo is outdated, however I lack permissions to edit the wiki directly. Would you be able to swap out 

`[<img src="http://static.squarespace.com/static/51eef63ae4b089778deccb24/t/522cb69be4b074119b21db97/1375925773732/Betterment.png" width="300"/>](https://www.betterment.com)`

with

`[![Betterment](https://www.betterment.com/hubfs/Graphics/shared-assets/betterment-logo.png)](https://www.betterment.com)`

Thanks!

**Comment by luke-hill** [comment]
Anyone can edit the wiki.

**Comment by CelticMajora** [comment]
> Anyone can edit the wiki.

The new page/edit buttons don't appear for me. Perhaps only repo maintainers can edit?
![Screen Shot 2022-06-14 at 10 14 12 AM](https://user-images.githubusercontent.com/12201885/173599318-0cda1b29-826d-4180-9618-e47c482d188f.png)

**Comment by luke-hill** [comment]
Try again now?? I wasn't aware but a setting was wrong.

**Comment by CelticMajora** [comment]
Was able to make the change. Thanks @luke-hill!
