### ISSUE TITLE
Require 'forwardable' somewhere in the project

### ISSUE THREAD

**Issue by Be-brand** [site-prism/site_prism#111]
# Issue to raise for SitePrism framework
## Environment
- Operating System (Mac / Windows / Ubuntu e.t.c.)
  - Ubuntu
- What Gems / Versions you are using (Specifically `site_prism` and `capybara`)
  - Ruby 3.1.0
  - site_prism 3.7.3
  - site_prism-all_there 0.3.2
  - capybara 3.37.1
- How you're interacting with the Framework (Cucumber Tests / RSpec Units / Minitest)
  - RSpec and Cucumber
- Browser/s Driver/s being used - with version numbers
  - Whatever the default is

## Expected Behavior
To be able to define a class extending `Section`, e.g. `class SomeSection < SitePrism::Section; end`

## Actual Behavior
An error occurs:
```
Failure/Error: class SomeSection < SitePrism::Section

NameError:
  uninitialized constant SitePrism::Section::Forwardable

      extend Forwardable
             ^^^^^^^^^^^
```

## Steps to reproduce
Simply run the line of code under Expected Behavior in a fresh project.

## Conclusion
Of course, this is very easily solvable by doing `require 'forwardable'` anywhere in the project, but it seems like this should be done in SitePrism.

**Comment by luke-hill** [comment]
Is this also a bug in earlier versions of SitePrism? Can you check 3.7 and 3.6 for me?

Yes I agree this is a simple f
