### ISSUE TITLE
Link to docs site is not working

### ISSUE THREAD

**Issue by scarroll32** [site-prism/site_prism#127]
From the README

> Find the pretty documentation here: https://rdoc.info/gems/site_prism/frames

This link is not working: https://rdoc.info/gems/site_prism/frames 

<img width="547" alt="Screenshot 2023-01-15 at 12 01 42" src="https://user-images.githubusercontent.com/11340230/212536914-301616cf-0232-401c-84a5-7afcf0cd788e.png">

**Comment by luke-hill** [comment]
That's because rdoc is playing up
There's is an alternative link here: https://www.rubydoc.info/github/site-prism/site_prism
