### ISSUE TITLE
[help needed] Programmatically set of an element

### ISSUE THREAD

**Issue by leoGalani** [site-prism/site_prism#13]
Hi,

Is there a way to set an `element` Programmatically?
The app I'm testing is a have a user of `[data-test-id]`. This identifier usually has an `id` that is related to a specific object of the application.

ex:
We have a list of users and each row have a `<li data-test-id="user-434353"> Name </li>`

What is the best approach to find those elements?

**Comment by leoGalani** [comment]
nothing that a page.find(*args) won't do. sorry for that :D

**Comment by luke-hill** [comment]
If you mean set an element through some code, yes you can, but we don't advise this.

That is metaprogramming something which is already metaprogrammed. Can you advise if you actually need this?

Could you not just refer to a plural element list like `elements :names, [data-test-id^="user"]`

**Comment by leoGalani** [comment]
No, because we have stuff like this:
```
"[data-test-id=category-item-#{id}-row]"
"[data-test-id=category-item-#{id}-name]"
"[data-test-id=section-item-#{id}-row]"

**Comment by luke-hill** [comment]
you can use or statements in your css selectors. Again, this is definitely possible, you just need to look into how to functionally do it.
