### ISSUE TITLE
2.14 has breaking changes

### ISSUE THREAD

**Issue by mathieujobin** [site-prism/site_prism#16]
# Issue to raise for SitePrism framework

I am trying to upgrade to the latest SitePrism and I found out the error I am getting started happening at 2.14

I can not find a mention about a breaking change in the changelog
https://github.com/site-prism/site_prism/blob/master/CHANGELOG.md#214---2018-06-22

it seems that a new validation was introduced to ensure Sections has child elements.
but in the large project I am working on, its not straight forward to defined all of those.
 
Note that I never setup site_prism and I dont have previous experience with this gem.

## Environment
- Operating System (Ubuntu)
- site_prism 2.14 up, capybara is locked at 2.18 until we can upgrade site_prism
- rspec 3.7.0

## Expected Behavior
my tests should pass.
I wish there might be a configuration option to maybe fallback to the previous behaviour
or sufficient documentation to help us upgrade.

I don't believe such breaking changes should have occurred before 3.0 IMO

## Actual Behavior

```
ArgumentError:
  You should provide descendant of SitePrism::Section class or/and a block as the second argument.
# /root/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/site_prism-2.14/lib/site_prism/element_container.rb:258:in `deduce_section_class'
# /root/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/site_prism-2.14/lib/site_prism/element_container.rb:247:in `extract_section_options'
# /root/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/site_prism-2.14/lib/site_prism/element_container.rb:77:in `sections'
# ./spec/page_objects/employees/totals_based_payroll_page.rb:8:in `<class:TotalsBasedPayrollPage>'
```

## Steps to reproduce
this is how my sections was defined
`sections :list_items, PayrollItem, 'tbody tr'`

**Comment by mathieujobin** [comment]
`PayrollItem` is an ActiveRecord::Base class, so that's why

**Comment by luke-hill** [comment]
Right yeh, so there's going to be a weird class conflict issue.

In 2.14 it is possible to define sections without a css locator (You already could define them with a block instead).

We introduced the concept of a default css / locator for sections. Hence the error complaining about the definition of your section.
