### ISSUE TITLE
Element traversal in tests using appium has slowed down.

### ISSUE THREAD

**Issue by kazuya-saeki** [site-prism/site_prism#208]
# Issue to raise for SitePrism framework
Using site_prism version 5.0beta or higher seems to slow down element traversal by a factor of 5.
Our 2 minute rspec test with appium now takes almost 10 minutes.

## Environment
- Operating System (Mac / Ubuntu)
- What Gems / Versions you are using ('appium_capybara', '3.0.0', 'capybara', '3.40.0', 'site_prism', '5.0.2')
- How you're interacting with the Framework (RSpec Units)

## Expected Behavior
Element search should be the same speed as in 4.0.3

## Actual Behavior
Element search is slow.

## Steps to reproduce
Run rspec for mobile using the above versions of appium, capybara , site_prism.

If you can't provide a link to a page that the problem can be reproduced on, please consider creating a reproducible page on [JSFiddle](https://jsfiddle.net/)

**Comment by kazuya-saeki** [comment]
Since this does not happen with 4.0.3, it would be very helpful if you could check for possible causes in the differences with 5.0.beta...

**Comment by luke-hill** [comment]
There isn't enough information here to reproduce @kazuya-saeki 

What kind of test?
What kind of operation?
What kind of webpage?

Have you checked the changes in UPGRADING.md

**Comment by kazuya-saeki** [comment]
> What kind of test?

The test will operate an Android application in the configuration of appium, capybara, and siteprism.

> What kind of operation?

Android applications are basically a native application screen, where you press buttons and input a little text while waiting for elements to appear, etc. Some parts of the application are operated by switching to WebView.

> What kind of webpage?

It was the app Native elements that were slow in retrieving elements, I have not been able to confirm what happens with WebView.

> Have you checked the changes in UPGRADING.md

Yes, I checked the changelog and lowered the version of the gem (site_prism-all_there) that looked a bit suspicious, but the behavior did not change. I couldn't figure out which commit I should rewind, so I'm posting this issue here.

**Comment by luke-hill** [comment]
Again there is no information for me to reproduce here. Please follow the guidelines in the template.

When I'm asking what kind of test / operation. I need something reproducible.

**Comment by luke-hill** [comment]
re-ping @kazuya-saeki
