### ISSUE TITLE
`title` is no longer allowed as the element name

### ISSUE THREAD

**Issue by HenryYan2012** [site-prism/site_prism#218]
# Issue to raise for SitePrism framework
`title` is no longer allowed as the element name.

## Environment
- Operating System: Mac
- site_prism v5.0.3
- Cucumber Tests
- Chrome v129.0.6668.70

## Expected Behavior
Allow the use of `title` as the element name.

## Actual Behavior
I have a section defined:
```ruby
class ResultSection < SitePrism::Section
        element :title, "td.title"
end
```
When I ran my tests I got an error:
```
site_prism-5.0.3/lib/site_prism/dsl/builder.rb:36:in `invalid_element_name': DSL item: title is invalid. Issue: name (blacklisted entry) (SitePrism::InvalidDSLNameError)
```

## Steps to reproduce
N/A

**Comment by whoojemaflip** [comment]
There are many examples in the project README using a `:title` attribute. Was this a deliberate change?

**Comment by luke-hill** [comment]
Hi there. So this is a valid error, coming from the error message you should see the problem.

Also see https://github.com/site-prism/site_prism/blob/main/UPGRADING.md#dsl-name-validation - If it's causing you an issue you can ban the execution of name validations by setting the environment variable.

As for the documentation issue. Noted, if you can push a PR to fix that it would be greatly appreciated.

**Comment by luke-hill** [comment]
Added more clarity here: https://github.com/site-prism/site_prism/pull/223 including fixing a minor bug

**Comment by zedtux** [comment]
Still the README.md file shows many usage of `:title`:
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L78-L81
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1141-L1146
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1178-L1181
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1246-L1253
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1266-L1269
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1304-L1307
* https://github.com/site-prism/site_prism/blob/e60d57bcb1dd64d6e5ca46f16d15d5643867b45a/README.md?plain=1#L1495-L1498
* etc...

**Comment by luke-hill** [comment]
Yes I've not amended those yet, I was waiting for someone to push a PR. But if one isn't forthcoming I'll remedy them when I get time. I've currently been having a go at restructuring the README using markdown titles.
