### ISSUE TITLE
A way to work code completion

### ISSUE THREAD

**Issue by serhatbolsu** [site-prism/site_prism#34]
I have classic element(s) and section(s) definitions on page classes. I would like to use code completion while searching for those.

Example, while using ruby mine, you can find the methods inside page object class but you can not find the elements. 
This would avoid wrong typing elements, 
Finding available elements much faster, 

Is there a pattern that I can change the page objects or `element` to support this?

**Comment by luke-hill** [comment]
I use RubyMine as well. And I feel you.

This is a very simple question, but one which I don't directly have a solution for.

The fundamental problem is based off the logic of how SitePrism works. It uses something called the MetaProgramming model. I.e. at compile time (obviously ruby doesn't compile, but bare with me). The program or AUT does NOT KNOW what methods or functions will be available to it.

Once the program is running, it dynamically generates these methods after the program has been switched on (not literally but bare with me).

How do we solve this issue. One of 3 ways.
1) We have an alternate metaprogram generator on the IDE, which scans these files real-time for the methods
2) We create a whitelist, and force users to maintain this (I'm very against this). This whitelist is then read against (Essentially duplicating all code)
3) We have a service created for us in RubyMine, which can accept dynamic calls from REST actions. This would then allow us to push these method names AFTER they have been generated

I have no idea on work scope, feasibility or timelines for any of those. Or even if anything else could be done. But very good question.

**Comment by serhatbolsu** [comment]
hi @luke-hill ty for fast response. 

Well sounds like IDE support is the way to go for me. otherwise it will go beyond the scope of library.
I would actually be willing to work on such project but its bit complex. 

Same problem existed in robotframework while a intellij plugin has been developed -> 
https://github.com/millennialmedia/intellibot
I can not support this project yet,but at least I have shown a good reference for implemantors
