### ISSUE TITLE
How can I wait for a section's element?

### ISSUE THREAD

**Issue by lflucasferreira** [site-prism/site_prism#39]
I stumbled upon a situation where I need to wait for an element that resides in a section block. I would like to know how can I solve this problem. Thank you!

**Comment by anuj-ssharma** [comment]
Have you tried any solutions so far ? 

It;s the same way that you wait if the element was not inside a section. The only thing that changes is that the element cannot be directly accessed via a page but via section. 

`
section_name.wait_until_element_name_visible
`

**Comment by lflucasferreira** [comment]
It worked like a charm, thanks!
