### ISSUE TITLE
SitePrism::ElementVisibilityTimeoutError on a Chrome headless mode

### ISSUE THREAD

**Issue by lflucasferreira** [site-prism/site_prism#41]
I updated the chromedriver to be the same as the Google Chrome browser: version 80.

The same code works perfectly on a `:selenium_chrome` mode, but it fails on a `:selenium_chrome_headless`.

It always returns `SitePrism::ElementVisibilityTimeoutError`, even passing a amount of seconds to wait for it.

## Environment
- Windows 10 Enterprise
- site_prism (3.4.2) & capybara (3.31.0)
- Cucumber
- ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185})

## Expected Behavior
The element is found between the set time.

## Actual Behavior
It fails with `SitePrism::ElementVisibilityTimeoutError`.

## Steps to reproduce
Piece of the code:

```
within_window(@topics_window) do
    @topics_page.wait_until_sorter_view_visible(wait: 10)
    @topics_page.sorter_view.click
    puts "\t#{'=' * 27} \n| Tópico Mais Visualizado |\n #{'=' * 27}"
    puts "\t#{@topics_page.topics.first.find('.title').text}"
end
```

**Comment by luke-hill** [comment]
This isn't enough information to reproduce.

We would need all the information. See www.sscce.org

**Comment by luke-hill** [comment]
ping @lflucasferreira Will close in 1 week if nothing heard.
