### ISSUE TITLE
`loaded?` should raise an error if there are no load validations

### ISSUE THREAD

**Issue by yjukaku** [site-prism/site_prism#45]
## Environment
- Mac
- `site_prism 3.4.1`, `capybara 3.30.0`
- RSpec
- Apparition

## Expected Behavior
`page.loaded? #=> raise exception if there are no load validations`

## Actual Behavior
`page.loaded? #=> true if there are no load validations`

## Steps to reproduce
```ruby
class ComplexPage < SitePrism::Page
  set_url "/complex-page"
  # nothing in here
end

complex_page = ComplexPage.new
# ...
click_on "Go to complex page"
expect(complex_page).to be_loaded
```

I think it's unexpected that `loaded?` returns `true` by default. If the page doesn't know how to check if it's been loaded (ie. there are no load validations defined) then it should raise an error.

**Comment by luke-hill** [comment]
There are other checks that occur beside load_validations. Furthermore, this `loaded?` check is done in 2 different ways.

What you are proposing would be a breaking change, and at best configurable with the default set to off.

The use case/s for this are the following

- #loaded? called as a boolean on a class instance
- #load being called on a class instance to load the initial page
- There is also a use case when calling `#when_loaded` however this is also called within the `#load`

Now also worth pointing out is that you can set an "in-line" validation for the check you are requesting, but this would not crash if they weren't seen, but more ignore them. this can be done with a `with_validations` set to false.

It is worth pointing out a PR which enhanced this "in-line" configuration would be accepted and merged into site-prism as a minor release. Should you be wanting to make this change, I'd happily review and accept. But changing the default behaviour is sadly a non-starter.

Hopefully this makes sense. I'll leave the topic open for a while for discussion.

**Comment by luke-hill** [comment]
https://github.com/site-prism/site_prism/blob/34a1ec938bee8c7cbd6dfba067d0747d65906c5e/README.md#skipping-load-validations
https://github.com/site-prism/site_prism/blob/a7a573139dfdb9df9f2d10b12920dce388364a12/CHANGELOG.md#32---2019-05-14

**Comment by luke-hill** [comment]
ping @yjukaku Any updates from you?

**Comment by yjukaku** [comment]
I think I misunderstood what `loaded?` checks for. You can go ahead and close this issue. Thanks!
