### ISSUE TITLE
Calling Section#within raises NoMethodError

### ISSUE THREAD

**Issue by palkan** [site-prism/site_prism#60]
## Environment
- Operating System:  Ubuntu
- Gems / Versions you are using:
  - site_prism 3.4.2
  - capybara 3.32.2
- How you're interacting with the Framework: Minitest (5.14.1)
- Browser/s Driver/s being used:
  - Remote chrome via `browserless/chrome:1.31-chrome-stable` Docker image
  - [Cuprite](https://github.com/rubycdp/cuprite) 0.10

## Expected Behavior

The following works as described in the docs:

```ruby
my_page.sections.first.within do
   assert_text "some text"
end

my_page.form.within do
   assert_text "some text"
end
```

## Actual Behavior

In both cases I see:

```
NoMethodError: undefined method `within' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element
```

## Steps to reproduce

I see these exceptions even for the simplest scenarios:

```ruby
class NewGroupPage < SitePrism::Page
  set_url "/groups/new"

  section :form, SitePrism::Section, "#new_message"

  load_validation { has_form? }
end

test "page should work" do
  page = NewGroupPage.new
  page.load

  page.form.within do
    assert_text "Save me"
  end
end
```

**Comment by luke-hill** [comment]
As a test can you try using SitePrism 3.5 - Which will downgrade capybara.

This may seem odd, but I think this error is similar to another one we have encountered (But not yet triaged fully).

**Comment by palkan** [comment]
Thanks! Downgrading works.

**Comment by luke-hill** [comment]
I appreciate this isn't a good fix for you at the moment. But I just haven't had time to investigate. We "believe" something in Capybara v3.30 broke some compatibility with us.

cc/ @tgaff

**Comment by tgaff** [comment]
Hmm I'll take a look. Also, hi 👋 @palkan thanks for the issue - I was just working with your ActionPolicy gem last week!

**Comment by simonc** [comment]
Hi there. Getting the same issue with `site_prime v3.7` and `capybara v3.33`. Was there any progress on the matter? May I help? ❤️

**Comment by luke-hill** [comment]
Can you create a new issue please @simonc including a full repro scenario.

this issue was the metaprogramming failing because of an internal breaking change we made in 3.6->3.7 - So 3.7 fixes the original issue.

**Comment by simonc** [comment]
Hi @luke-hill! Thanks!

Actually I just found out that there was a call to `within` inside a PageObject, something like
```ruby
class SomePage < SitePrism::Page
  def set_language(lang)
    within('select.lang') do
      find("option[value='#{lang}']").select_option
    end
  end
end
```
I must come from an ancient era ^^ Switching to this fixed it:
```ruby
class SomePage < SitePrism::Page
  def set_language(lang)
    find('select.lang').within do |s|
      s.find("option[value='#{lang}']").select_option
    end
  end
end
```

_(I know it should be listed as an `element` of the page, it's actually a simplified version for the sake of future readers.)_
