### ISSUE TITLE
SitePrism does not delegate Capybara in-built matchers to root_element (3.30 bug)

### ISSUE THREAD

**Issue by luke-hill** [site-prism/site_prism#62]
# Issue to raise for SitePrism framework
When running capybara matchers, the `current_scope` failure is only triggered for have_link. have_text seems to be fine. Maybe worth investigating more.

@tgaff - This is the 3.30 bug we found with capybara.

## Environment
- N/A

## Expected Behavior
test runs

## Actual Behavior
current_scope failure

## Steps to reproduce
use `have_link` on site_prism 3.42 with capybara > 3.30

**Comment by HashNotAdam** [comment]
I'm unable to reproduce this in SitePrism 3.6
The old version of Capybara is causing me issues so, if this is still an issue, I'd like to help get it fixed

**Comment by luke-hill** [comment]
@HashNotAdam This is now 60-70% fixed. The next version of site_prism will unlock capybara restrictions.
