### ISSUE TITLE
Can't match Section values with composable matchers

### ISSUE THREAD

**Issue by alan-pie** [site-prism/site_prism#63]
I have a table in a page that returns items that match certain filters. I am trying to write a test that verifies those rows have the correct values as the filters change, but I am unable to do this cleanly using matcher composition.

Here is some simplified code demonstrating the issue

```ruby
class Row < SitePrism::Section
  element :valueA, 'td:nth-of-type(3)'
  element :valueB, 'td:nth-of-type(2)'
end

class TablePage < SitePrism::Page
  set_url '/table_page'
  sections :rows, OrderTableRow, '#my_table tbody tr'
end

describe 'table page' do
  it 'updates the table with changing filters' do
    items = []
    items << createItem(valA: 'foo', valB: 'bar')
    items << createItem(valA: 'baz', valB: 'boz')
    item_matchers = items.map do |i|
      have_attributes(valueA: have_text(i.valA), valueB: have_text(i.valB))
    end
    
    p = TablePage.new
    p.load
    expect(p).to have_rows(count: 2)
    expect(p.rows[0].valueA).to have_text(items[0].valA) # this passes
    expect(p.rows[0]).to have_attributes(valueA: items[0].valA) # this gives an error that valueA is a Capybara::Node::Element
    expect(p.rows[0]).to match(valueA: items[0].valA) # this gives an error that valueA is a Row
    expect(p.rows).to match(item_matchers) # this is what I want to write but gives the error above
end
```

**Comment by luke-hill** [comment]
I'm guessing createItem is some sort of stub that providers reader methods like a struct.

I'm not really sure what you're looking to test here. Are you using something like factorybot to populate a page and then you want to test the page. Why don't you just use an equality matcher?

Something like

```
page = TablePage.new
page.load
value_a_texts = page.rows.map { |row| row.valueA.text }
value_b_texts = page.rows.map { |row| row.valueB.text }
static_array_a = # You need to get this from factorybot or whatever
static_array_b = # You need to get this from factorybot or whatever

expect(value_a_texts).to eq(static_array_a)
expect(value_b_texts).to eq(static_array_b)
```

**Comment by alan-pie** [comment]
createItem creates items in a database with factorybot. The test is for the browser where the items are rendered in an HTML table. I want to test that as I change the filters on the table that the correct set of orders is rendered. There are a lot of fields in each row so it would be a lot of duplicated code to pull out all individual fields each time. I could check for just one of the fields in each row or write a custom matcher but I was hoping to avoid that for something that is really just a composition of ordinary matchers.

This is a higher level view of what I'm trying to do:

```ruby
# create the items in the database
# load the page
# check all the items are in the table with the right values
# change the filter
# check the correct items are in the table with the right values
# change the filter
# check the correct items are in the table with the right values
# change the filter
# check the correct items are in the table with the right values
```

**Comment by luke-hill** [comment]
What I've suggested would work fine then.

When you create the values, I'm guessing you're returned a static array with what you created - Or you must have some way of comparing all of the values you created with all the values visible.

then if you were doing this 10/20/30 times with different values, you could use a method

```
value_a_texts = page.rows.map { |row| row.valueA.text }
```

becomes

```
def text_array_from(value)
  page.rows.map { |row| row.send(value).text }
end
```

**Comment by luke-hill** [comment]
Closing as a non-issue. Feel free to re-open is issue is reproducible.
