### ISSUE TITLE
Support for finding inputs by value, i.e. Capybara find_field query options

### ISSUE THREAD

**Issue by alan-pie** [site-prism/site_prism#71]
## Expected Behavior
If I have an element that represents an input element with a value, I should be able to wait for that element to be visible with a particular value like Capybara's find_field(id: 'someid', with: 'somefieldvalue')

E.g.
class MyPage < SitePrism::Page
  element :my_input, '#input-id'
end

page = MyPage.new
page.load
page.wait_for_my_input_visible(with: 'somefieldvalue')

## Actual Behavior
page.wait_for_my_input_visible(text: 'somefieldvalue') is the closest I can get and it does not work.

**Comment by luke-hill** [comment]
You would create the original element with whatever capybara finders you required. Then you would call `page.wait_for_my_input_visible`
```
class MyPage < SitePrism::Page
  element :my_input, '#input-id[value="something"]', other_locator: 'thing', text: 'yepoaw'
end
```

**Comment by alan-pie** [comment]
Thanks Luke. It would be very useful to be able to do this with an element that doesn't have the value specified so the number of elements I need to declare in the page doesn't increase with the number of values they might hold and supports values that are dynamic without having to parameterize the Page object itself.

**Comment by luke-hill** [comment]
You can create an element using an iVar, and then use an attr_reader/writer to set those values.

NB: Alter `initialize` at your peril. Do this as a standalone reader/writer, NOT on page initialization.

i.e.

```
class Page
  attr_writer :my_ivar

  element :dynamic_element, @my_ivar
```
```
page = Page.new
page.my_ivar = ".class-one"
page.my_ivar # ".class-one"
page.dynamic_element # Capybara::Node::Element
```
