### ISSUE TITLE
Unclear if "click" waits for element to be visible

### ISSUE THREAD

**Issue by alan-pie** [site-prism/site_prism#73]
Does click wait for an element to be visible before clicking it or does it depend on certain factors or Capybara settings? If so, which ones?

I have a flaky test where clicking a link sometimes brings us to the linked page and sometimes does not and no request for that page is sent to the server. I'm wondering if it's because the link is not yet visible.

**Comment by luke-hill** [comment]
It follows the standard webdriver spec. If you have implicit waits configured then they will be observed. Alternatively use a waiter.

The README has a whole bunch of info on waiting. If you feel as though the info isn't there, feel free to submit a PR to alter the README.
