### ISSUE TITLE
Documentation link broken http://rdoc.info/gems/site_prism/frames

### ISSUE THREAD

**Issue by asavageiv** [site-prism/site_prism#74]
The following link in the README is broken
> Find the pretty documentation here: http://rdoc.info/gems/site_prism/frames

**Comment by luke-hill** [comment]
Good spot - Feel free to submit a PR, for small PR's you can submit a change by clicking the 3dots at the top right of the file.

**Comment by asavageiv** [comment]
What is the correct link? I couldn't find a working one on rdoc.info.

**Comment by luke-hill** [comment]
https://rdoc.info/gems/site_prism/frames seems to work for me. I don't use this website so not sure sorry
