### ISSUE TITLE
How to fill input dates when I've mapped them with Site Prism?

### ISSUE THREAD

**Issue by filipeltsilva** [site-prism/site_prism#88]
I'm developing automated tests with SitePrism, Ruby and Capybara and I didn't find a way to fill input dates when I'm using Site Prism.

I know I can use the Capybara's fill_in method and pass the field and the value in the parameters. But when I map the field in a page object, fill_in is not enough to my automation write the input date field with the date.

How can I work with Site Prism and Capybara together in this case, if it's possible?

Thanks!

**Comment by luke-hill** [comment]
It depends on what type of object it is. If it's a native datepicker, click it, then click on the modal that appears.

You'd have something like

```
element :datepicker, 'selector'
elements :datepicker_dates 'selector a'
```

And in your code you'd do.

```
datepicker.click
datepicker_dates[index].click
```
